package com.example.chat

import java.util.Locale

enum class AppLanguage {
    EN,
    ZH;

    companion object {
        fun fromStored(value: String?): AppLanguage =
            when (value?.uppercase(Locale.ROOT)) {
                "ZH" -> ZH
                else -> EN
            }

        fun systemDefault(): AppLanguage =
            if (Locale.getDefault().language.startsWith("zh", ignoreCase = true)) ZH else EN
    }
}

enum class AppDisplayMode {
    SYSTEM,
    LIGHT,
    DARK;

    companion object {
        fun fromStored(value: String?): AppDisplayMode =
            when (value?.uppercase(Locale.ROOT)) {
                "LIGHT" -> LIGHT
                "DARK" -> DARK
                else -> SYSTEM
            }
    }
}

data class AppStrings(
    val appName: String,
    val appSubtitle: String,
    val serverUrl: String,
    val username: String,
    val password: String,
    val login: String,
    val connected: String,
    val disconnected: String,
    val roomSecret: String,
    val e2ee: String,
    val settings: String,
    val deleteHistory: String,
    val deleteHistoryConfirm: String,
    val delete: String,
    val cancel: String,
    val changePassword: String,
    val changeUsername: String,
    val changeAvatar: String,
    val avatarHint: String,
    val userId: String,
    val newPassword: String,
    val newUsername: String,
    val usernameEmpty: String,
    val invalidUsername: String,
    val usernameTaken: String,
    val unableToChangeUsername: String,
    val save: String,
    val replyingTo: String,
    val typeMessage: String,
    val unreadMessages: String,
    val open: String,
    val downloadOpen: String,
    val encryptedMessage: String,
    val unableToDecrypt: String,
    val encryptedAttachment: String,
    val tapOpen: String,
    val image: String,
    val voiceNote: String,
    val file: String,
    val language: String,
    val displayMode: String,
    val followSystem: String,
    val lightMode: String,
    val darkMode: String,
    val systemColors: String,
    val systemColorsHint: String,
    val backAgainToExit: String,
    val logout: String,
    val refresh: String,
    val admin: String,
    val statusSeparator: String,
    val showMenu: String,
    val hideMenu: String,
    val addMedia: String,
    val takePhoto: String,
    val startVoice: String,
    val sendVoice: String,
    val recording: String,
    val holdToTalk: String,
    val releaseToSend: String,
    val releaseToCancel: String,
    val keyboardInput: String,
    val play: String,
    val pause: String,
    val uploading: String,
    val downloading: String,
    val recalledMessage: String,
    val longPressRecall: String,
    val attachmentRemoved: String,
    val recallAction: String,
    val currentVersion: String,
    val latestVersion: String,
    val checkUpdate: String,
    val installUpdate: String,
    val latestVersionInstalled: String,
    val updateAvailable: String,
    val updatePromptTitle: String,
    val updatePromptBody: String,
    val updateNow: String,
    val later: String,
    val noReleaseUploaded: String,
    val checkingUpdate: String,
    val updateDownloaded: String,
    val downloadUpdate: String,
    val openInstaller: String,
    val prereleaseBuilds: String,
    val prereleaseCenter: String,
    val prereleaseAvailable: String,
    val noPrereleaseUploaded: String,
    val sendPhoto: String,
    val cameraPermissionDenied: String,
    val cameraUnavailable: String,
    val cameraCaptureFailed: String,
    val sendFailed: String,
    val retrySend: String,
    val retrySendConfirm: String,
    val voiceCall: String,
    val incomingCall: String,
    val calling: String,
    val callConnecting: String,
    val callActive: String,
    val callEnded: String,
    val callRejected: String,
    val callBusy: String,
    val callUnavailable: String,
    val callReconnecting: String,
    val callConnectionLost: String,
    val callFailed: String,
    val accept: String,
    val decline: String,
    val endCall: String,
    val mute: String,
    val unmute: String,
    val audioOutput: String,
    val speaker: String,
    val earpiece: String,
    val bluetooth: String,
    val minimizeCall: String,
    val returnToCall: String,
    val overlayPermissionHint: String,
    val microphonePermissionDenied: String,
    val directCallOnly: String,
    val today: String,
    val yesterday: String,
)

fun stringsFor(language: AppLanguage): AppStrings =
    when (language) {
        AppLanguage.ZH -> AppStrings(
            appName = "E2EE Chat",
            appSubtitle = "\u81ea\u6258\u7ba1\u52a0\u5bc6\u804a\u5929 Android \u5ba2\u6237\u7aef",
            serverUrl = "\u670d\u52a1\u5668\u5730\u5740",
            username = "\u7528\u6237\u540d",
            password = "\u5bc6\u7801",
            login = "\u767b\u5f55",
            connected = "\u5df2\u8fde\u63a5",
            disconnected = "\u672a\u8fde\u63a5",
            roomSecret = "\u623f\u95f4\u5bc6\u94a5",
            e2ee = "\u7aef\u5230\u7aef\u52a0\u5bc6",
            settings = "\u8bbe\u7f6e",
            deleteHistory = "\u6e05\u7a7a\u8bb0\u5f55",
            deleteHistoryConfirm = "\u786e\u8ba4\u6e05\u7a7a\u6240\u6709\u4eba\u7684\u804a\u5929\u8bb0\u5f55\u5417\uff1f",
            delete = "\u5220\u9664",
            cancel = "\u53d6\u6d88",
            changePassword = "\u4fee\u6539\u5bc6\u7801",
            changeUsername = "\u4fee\u6539\u7528\u6237\u540d",
            changeAvatar = "\u66f4\u6362\u5934\u50cf",
            avatarHint = "\u4e0a\u4f20\u4e00\u5f20\u65b0\u5934\u50cf",
            userId = "ID",
            newPassword = "\u65b0\u5bc6\u7801",
            newUsername = "\u65b0\u7528\u6237\u540d",
            usernameEmpty = "\u7528\u6237\u540d\u4e0d\u80fd\u4e3a\u7a7a",
            invalidUsername = "\u7528\u6237\u540d\u9700\u4e3a 2-24 \u4f4d\uff0c\u53ea\u80fd\u5305\u542b\u5b57\u6bcd\u3001\u6570\u5b57\u3001\u4e0b\u5212\u7ebf\u3001\u6a2a\u7ebf\u6216\u4e2d\u6587",
            usernameTaken = "\u8fd9\u4e2a\u7528\u6237\u540d\u5df2\u88ab\u5360\u7528",
            unableToChangeUsername = "\u65e0\u6cd5\u4fee\u6539\u7528\u6237\u540d",
            save = "\u4fdd\u5b58",
            replyingTo = "\u6b63\u5728\u56de\u590d",
            typeMessage = "\u8f93\u5165\u6d88\u606f",
            unreadMessages = "\u672a\u8bfb\u6d88\u606f",
            open = "\u6253\u5f00",
            downloadOpen = "\u4e0b\u8f7d / \u6253\u5f00",
            encryptedMessage = "\u52a0\u5bc6\u6d88\u606f",
            unableToDecrypt = "\u65e0\u6cd5\u89e3\u5bc6",
            encryptedAttachment = "\u52a0\u5bc6\u9644\u4ef6",
            tapOpen = "\u89e3\u5bc6\u540e\u70b9\u6253\u5f00",
            image = "\u56fe\u7247",
            voiceNote = "\u8bed\u97f3",
            file = "\u6587\u4ef6",
            language = "\u8bed\u8a00",
            displayMode = "\u663e\u793a\u6a21\u5f0f",
            followSystem = "\u8ddf\u968f\u7cfb\u7edf",
            lightMode = "\u4eae\u8272",
            darkMode = "\u6697\u8272",
            systemColors = "\u7cfb\u7edf\u914d\u8272",
            systemColorsHint = "Android 12 \u53ca\u4ee5\u4e0a\u4f1a\u4f7f\u7528\u7cfb\u7edf\u52a8\u6001\u914d\u8272",
            backAgainToExit = "\u518d\u6309\u4e00\u6b21\u8fd4\u56de\u952e\u9000\u51fa",
            logout = "\u9000\u51fa\u767b\u5f55",
            refresh = "\u5237\u65b0",
            admin = "\u7ba1\u7406\u5458",
            statusSeparator = " | ",
            showMenu = "\u5c55\u5f00\u83dc\u5355",
            hideMenu = "\u6536\u8d77\u83dc\u5355",
            addMedia = "\u6dfb\u52a0",
            takePhoto = "\u62cd\u7167",
            startVoice = "\u5f00\u59cb\u5f55\u97f3",
            sendVoice = "\u53d1\u9001\u5f55\u97f3",
            recording = "\u5f55\u97f3\u4e2d",
            holdToTalk = "\u6309\u4f4f\u8bf4\u8bdd",
            releaseToSend = "\u677e\u5f00\u53d1\u9001",
            releaseToCancel = "\u4e0a\u6ed1\u53d6\u6d88\uff0c\u677e\u5f00\u53d6\u6d88",
            keyboardInput = "\u952e\u76d8",
            play = "\u64ad\u653e",
            pause = "\u6682\u505c",
            uploading = "\u4e0a\u4f20\u4e2d",
            downloading = "\u4e0b\u8f7d\u4e2d",
            recalledMessage = "\u5df2\u64a4\u56de\u4e00\u6761\u6d88\u606f",
            longPressRecall = "\u957f\u6309\u53ef\u64a4\u56de",
            attachmentRemoved = "\u9644\u4ef6\u5df2\u88ab\u7ba1\u7406\u5458\u6e05\u7406",
            recallAction = "\u64a4\u56de",
            currentVersion = "\u5f53\u524d\u7248\u672c",
            latestVersion = "\u670d\u52a1\u5668\u7248\u672c",
            checkUpdate = "\u68c0\u67e5\u66f4\u65b0",
            installUpdate = "\u4e0b\u8f7d\u5e76\u5b89\u88c5",
            latestVersionInstalled = "\u5df2\u662f\u6700\u65b0\u7248\u672c",
            updateAvailable = "\u53d1\u73b0\u65b0\u7248\u672c\u53ef\u7528",
            updatePromptTitle = "\u53d1\u73b0\u65b0\u7248\u672c",
            updatePromptBody = "\u68c0\u6d4b\u5230\u65b0\u7248\u672c\uff0c\u8bf7\u5c3d\u5feb\u66f4\u65b0",
            updateNow = "\u53bb\u66f4\u65b0",
            later = "\u7a0d\u540e",
            noReleaseUploaded = "\u670d\u52a1\u5668\u8fd8\u6ca1\u6709\u4e0a\u4f20\u5b89\u88c5\u5305",
            checkingUpdate = "\u68c0\u67e5\u66f4\u65b0\u4e2d",
            updateDownloaded = "\u5b89\u88c5\u5305\u5df2\u4e0b\u8f7d\uff0c\u8bf7\u7ee7\u7eed\u5b89\u88c5",
            downloadUpdate = "\u4e0b\u8f7d\u66f4\u65b0",
            openInstaller = "\u5b89\u88c5\u66f4\u65b0",
            prereleaseBuilds = "\u6d4b\u8bd5\u7248",
            prereleaseCenter = "\u6d4b\u8bd5\u7248\u4e0b\u8f7d",
            prereleaseAvailable = "\u670d\u52a1\u5668\u6709\u65b0\u7684\u6d4b\u8bd5\u7248",
            noPrereleaseUploaded = "\u670d\u52a1\u5668\u8fd8\u6ca1\u6709\u4e0a\u4f20\u6d4b\u8bd5\u7248 APK",
            sendPhoto = "\u53d1\u9001\u7167\u7247",
            cameraPermissionDenied = "\u9700\u8981\u76f8\u673a\u6743\u9650\u624d\u80fd\u62cd\u7167",
            cameraUnavailable = "\u76f8\u673a\u6682\u65f6\u65e0\u6cd5\u6253\u5f00",
            cameraCaptureFailed = "\u62cd\u7167\u5931\u8d25",
            sendFailed = "\u53d1\u9001\u5931\u8d25",
            retrySend = "\u91cd\u65b0\u53d1\u9001",
            retrySendConfirm = "\u8981\u91cd\u65b0\u53d1\u9001\u8fd9\u6761\u6d88\u606f\u5417\uff1f",
            voiceCall = "\u8bed\u97f3\u901a\u8bdd",
            incomingCall = "\u6765\u7535",
            calling = "\u6b63\u5728\u62e8\u53f7",
            callConnecting = "\u8fde\u63a5\u4e2d",
            callActive = "\u901a\u8bdd\u4e2d",
            callEnded = "\u901a\u8bdd\u5df2\u7ed3\u675f",
            callRejected = "\u5bf9\u65b9\u5df2\u62d2\u7edd",
            callBusy = "\u5bf9\u65b9\u6b63\u5728\u901a\u8bdd\u4e2d",
            callUnavailable = "\u5bf9\u65b9\u6682\u65f6\u65e0\u6cd5\u63a5\u542c",
            callReconnecting = "\u7f51\u7edc\u4e0d\u4f73\uff0c\u6b63\u5728\u91cd\u8fde",
            callConnectionLost = "\u901a\u8bdd\u4fe1\u4ee4\u5df2\u65ad\u5f00",
            callFailed = "\u901a\u8bdd\u5931\u8d25",
            accept = "\u63a5\u542c",
            decline = "\u62d2\u7edd",
            endCall = "\u6302\u65ad",
            mute = "\u9759\u97f3",
            unmute = "\u53d6\u6d88\u9759\u97f3",
            audioOutput = "\u97f3\u9891\u8f93\u51fa",
            speaker = "\u514d\u63d0",
            earpiece = "\u542c\u7b52",
            bluetooth = "\u84dd\u7259\u8033\u673a",
            minimizeCall = "\u6700\u5c0f\u5316\u901a\u8bdd",
            returnToCall = "\u8fd4\u56de\u901a\u8bdd",
            overlayPermissionHint = "\u9700\u5141\u8bb8\u663e\u793a\u5728\u5176\u4ed6\u5e94\u7528\u4e0a\u65b9\uff0c\u624d\u80fd\u5728\u684c\u9762\u663e\u793a\u901a\u8bdd\u6d6e\u7a97",
            microphonePermissionDenied = "\u9700\u8981\u9ea6\u514b\u98ce\u6743\u9650\u624d\u80fd\u901a\u8bdd",
            directCallOnly = "\u53ea\u80fd\u5728\u5355\u804a\u4e2d\u53d1\u8d77\u8bed\u97f3\u901a\u8bdd",
            today = "\u4eca\u5929",
            yesterday = "\u6628\u5929",
        )

        AppLanguage.EN -> AppStrings(
            appName = "E2EE Chat",
            appSubtitle = "Android client for self-hosted encrypted chat.",
            serverUrl = "Server URL",
            username = "Username",
            password = "Password",
            login = "Login",
            connected = "Connected",
            disconnected = "Disconnected",
            roomSecret = "Room secret",
            e2ee = "E2EE",
            settings = "Settings",
            deleteHistory = "Delete history",
            deleteHistoryConfirm = "Delete all messages for everyone?",
            delete = "Delete",
            cancel = "Cancel",
            changePassword = "Change password",
            changeUsername = "Change username",
            changeAvatar = "Change avatar",
            avatarHint = "Upload a new avatar",
            userId = "ID",
            newPassword = "New password",
            newUsername = "New username",
            usernameEmpty = "Username cannot be empty",
            invalidUsername = "Username must be 2-24 characters and use letters, numbers, underscores, hyphens, or Chinese characters",
            usernameTaken = "That username is already taken",
            unableToChangeUsername = "Unable to change username",
            save = "Save",
            replyingTo = "Replying to",
            typeMessage = "Type a message",
            unreadMessages = "Unread messages",
            open = "Open",
            downloadOpen = "Download / Open",
            encryptedMessage = "Encrypted message",
            unableToDecrypt = "Unable to decrypt",
            encryptedAttachment = "Encrypted attachment",
            tapOpen = "Tap open after decrypt",
            image = "Image",
            voiceNote = "Voice note",
            file = "File",
            language = "Language",
            displayMode = "Display mode",
            followSystem = "Follow system",
            lightMode = "Light",
            darkMode = "Dark",
            systemColors = "System colors",
            systemColorsHint = "On Android 12+, use the system dynamic color palette",
            backAgainToExit = "Press back again to exit",
            logout = "Logout",
            refresh = "Refresh",
            admin = "admin",
            statusSeparator = " | ",
            showMenu = "Show menu",
            hideMenu = "Hide menu",
            addMedia = "Add",
            takePhoto = "Take photo",
            startVoice = "Start voice",
            sendVoice = "Send voice",
            recording = "Recording",
            holdToTalk = "Hold to talk",
            releaseToSend = "Release to send",
            releaseToCancel = "Slide up to cancel",
            keyboardInput = "Keyboard",
            play = "Play",
            pause = "Pause",
            uploading = "Uploading",
            downloading = "Downloading",
            recalledMessage = "Message recalled",
            longPressRecall = "Long press to recall",
            attachmentRemoved = "Attachment removed by admin",
            recallAction = "Recall",
            currentVersion = "Current version",
            latestVersion = "Server version",
            checkUpdate = "Check update",
            installUpdate = "Download and install",
            latestVersionInstalled = "You already have the latest version",
            updateAvailable = "A newer version is available",
            updatePromptTitle = "Update available",
            updatePromptBody = "A new version was detected. Please update as soon as possible.",
            updateNow = "Update now",
            later = "Later",
            noReleaseUploaded = "No release APK has been uploaded yet",
            checkingUpdate = "Checking for updates",
            updateDownloaded = "Update downloaded. Continue to install",
            downloadUpdate = "Download update",
            openInstaller = "Install update",
            prereleaseBuilds = "Prerelease",
            prereleaseCenter = "Prerelease downloads",
            prereleaseAvailable = "A new prerelease build is on the server",
            noPrereleaseUploaded = "No prerelease APK has been uploaded yet",
            sendPhoto = "Send photo",
            cameraPermissionDenied = "Camera permission is required",
            cameraUnavailable = "Camera is currently unavailable",
            cameraCaptureFailed = "Unable to capture photo",
            sendFailed = "Send failed",
            retrySend = "Retry send",
            retrySendConfirm = "Retry sending this message?",
            voiceCall = "Voice call",
            incomingCall = "Incoming call",
            calling = "Calling",
            callConnecting = "Connecting",
            callActive = "In call",
            callEnded = "Call ended",
            callRejected = "Call rejected",
            callBusy = "The other side is busy",
            callUnavailable = "The other side is unavailable",
            callReconnecting = "Poor network, trying to reconnect",
            callConnectionLost = "Call signaling disconnected",
            callFailed = "Call failed",
            accept = "Accept",
            decline = "Decline",
            endCall = "End call",
            mute = "Mute",
            unmute = "Unmute",
            audioOutput = "Audio output",
            speaker = "Speaker",
            earpiece = "Earpiece",
            bluetooth = "Bluetooth",
            minimizeCall = "Minimize call",
            returnToCall = "Return to call",
            overlayPermissionHint = "Allow display over other apps to show the floating call bubble on the desktop",
            microphonePermissionDenied = "Microphone permission is required for calls",
            directCallOnly = "Voice calls are only available in direct chats",
            today = "Today",
            yesterday = "Yesterday",
        )
    }
